spec = {
    'api__test': {'method': 'post',
                  'path': '/api.test'},
    'auth__revoke': {'method': 'post',
                     'path': '/auth.revoke'},
    'auth__test': {'method': 'post',
                   'path': '/auth.test'},
    'bots__info': {'method': 'post',
                   'path': '/bots.info'},
    'channels__archive': {'method': 'post',
                          'path': '/channels.archive'},
    'channels__create': {'method': 'post',
                         'path': '/channels.create'},
    'channels__history': {'method': 'post',
                          'path': '/channels.history'},
    'channels__info': {'method': 'post',
                       'path': '/channels.info'},
    'channels__invite': {'method': 'post',
                         'path': '/channels.invite'},
    'channels__join': {'method': 'post',
                       'path': '/channels.join'},
    'channels__kick': {'method': 'post',
                       'path': '/channels.kick'},
    'channels__leave': {'method': 'post',
                        'path': '/channels.leave'},
    'channels__list': {'method': 'post',
                       'path': '/channels.list'},
    'channels__mark': {'method': 'post',
                       'path': '/channels.mark'},
    'channels__rename': {'method': 'post',
                         'path': '/channels.rename'},
    'channels__replies': {'method': 'post',
                          'path': '/channels.replies'},
    'channels__set_purpose': {'method': 'post',
                             'path': '/channels.setPurpose'},
    'channels__set_topic': {'method': 'post',
                           'path': '/channels.setTopic'},
    'channels__unarchive': {'method': 'post',
                            'path': '/channels.unarchive'},
    'chat__delete': {'method': 'post',
                     'path': '/chat.delete'},
    'chat__me_message': {'method': 'post',
                        'path': '/chat.meMessage'},
    'chat__post_message': {'method': 'post',
                          'path': '/chat.postMessage'},
    'chat__unfurl': {'method': 'post',
                     'path': '/chat.unfurl'},
    'chat__update': {'method': 'post',
                     'path': '/chat.update'},
    'dnd__end_dnd': {'method': 'post',
                    'path': '/dnd.endDnd'},
    'dnd__end_snooze': {'method': 'post',
                       'path': '/dnd.endSnooze'},
    'dnd__info': {'method': 'post',
                  'path': '/dnd.info'},
    'dnd__set_snooze': {'method': 'post',
                       'path': '/dnd.setSnooze'},
    'dnd__team_info': {'method': 'post',
                      'path': '/dnd.teamInfo'},
    'emoji__list': {'method': 'post',
                    'path': '/emoji.list'},
    'files__comments__add': {'method': 'post',
                             'path': '/files.comments.add'},
    'files__comments__delete': {'method': 'post',
                                'path': '/files.comments.delete'},
    'files__comments__edit': {'method': 'post',
                              'path': '/files.comments.edit'},
    'files__delete': {'method': 'post',
                      'path': '/files.delete'},
    'files__info': {'method': 'post',
                    'path': '/files.info'},
    'files__list': {'method': 'post',
                    'path': '/files.list'},
    'files__revoke_public_url': {'method': 'post',
                               'path': '/files.revokePublicURL'},
    'files__shared_public_url': {'method': 'post',
                               'path': '/files.sharedPublicURL'},
    'files__upload': {'method': 'post',
                      'path': '/files.upload'},
    'groups__archive': {'method': 'post',
                        'path': '/groups.archive'},
    'groups__close': {'method': 'post',
                      'path': '/groups.close'},
    'groups__create': {'method': 'post',
                       'path': '/groups.create'},
    'groups__create_child': {'method': 'post',
                            'path': '/groups.createChild'},
    'groups__history': {'method': 'post',
                        'path': '/groups.history'},
    'groups__info': {'method': 'post',
                     'path': '/groups.info'},
    'groups__invite': {'method': 'post',
                       'path': '/groups.invite'},
    'groups__kick': {'method': 'post',
                     'path': '/groups.kick'},
    'groups__leave': {'method': 'post',
                      'path': '/groups.leave'},
    'groups__list': {'method': 'post',
                     'path': '/groups.list'},
    'groups__mark': {'method': 'post',
                     'path': '/groups.mark'},
    'groups__open': {'method': 'post',
                     'path': '/groups.open'},
    'groups__rename': {'method': 'post',
                       'path': '/groups.rename'},
    'groups__replies': {'method': 'post',
                        'path': '/groups.replies'},
    'groups__set_purpose': {'method': 'post',
                           'path': '/groups.setPurpose'},
    'groups__set_topic': {'method': 'post',
                         'path': '/groups.setTopic'},
    'groups__unarchive': {'method': 'post',
                          'path': '/groups.unarchive'},
    'im__close': {'method': 'post',
                  'path': '/im.close'},
    'im__history': {'method': 'post',
                    'path': '/im.history'},
    'im__list': {'method': 'post',
                 'path': '/im.list'},
    'im__mark': {'method': 'post',
                 'path': '/im.mark'},
    'im__open': {'method': 'post',
                 'path': '/im.open'},
    'im__replies': {'method': 'post',
                    'path': '/im.replies'},
    'mpim__close': {'method': 'post',
                    'path': '/mpim.close'},
    'mpim__history': {'method': 'post',
                      'path': '/mpim.history'},
    'mpim__list': {'method': 'post',
                   'path': '/mpim.list'},
    'mpim__mark': {'method': 'post',
                   'path': '/mpim.mark'},
    'mpim__open': {'method': 'post',
                   'path': '/mpim.open'},
    'mpim__replies': {'method': 'post',
                      'path': '/mpim.replies'},
    'oauth__access': {'method': 'post',
                      'path': '/oauth.access'},
    'pins__add': {'method': 'post',
                  'path': '/pins.add'},
    'pins__list': {'method': 'post',
                   'path': '/pins.list'},
    'pins__remove': {'method': 'post',
                     'path': '/pins.remove'},
    'reactions__add': {'method': 'post',
                       'path': '/reactions.add'},
    'reactions__get': {'method': 'post',
                       'path': '/reactions.get'},
    'reactions__list': {'method': 'post',
                        'path': '/reactions.list'},
    'reactions__remove': {'method': 'post',
                          'path': '/reactions.remove'},
    'reminders__add': {'method': 'post',
                       'path': '/reminders.add'},
    'reminders__complete': {'method': 'post',
                            'path': '/reminders.complete'},
    'reminders__delete': {'method': 'post',
                          'path': '/reminders.delete'},
    'reminders__info': {'method': 'post',
                        'path': '/reminders.info'},
    'reminders__list': {'method': 'post',
                        'path': '/reminders.list'},
    'rtm__connect': {'method': 'post',
                     'path': '/rtm.connect'},
    'rtm__start': {'method': 'post',
                   'path': '/rtm.start'},
    'search__all': {'method': 'post',
                    'path': '/search.all'},
    'search__files': {'method': 'post',
                      'path': '/search.files'},
    'search__messages': {'method': 'post',
                         'path': '/search.messages'},
    'stars__add': {'method': 'post',
                   'path': '/stars.add'},
    'stars__list': {'method': 'post',
                    'path': '/stars.list'},
    'stars__remove': {'method': 'post',
                      'path': '/stars.remove'},
    'team__access_logs': {'method': 'post',
                         'path': '/team.accessLogs'},
    'team__billable_info': {'method': 'post',
                           'path': '/team.billableInfo'},
    'team__info': {'method': 'post',
                   'path': '/team.info'},
    'team__integration_logs': {'method': 'post',
                              'path': '/team.integrationLogs'},
    'team__profile__get': {'method': 'post',
                           'path': '/team.profile.get'},
    'usergroups__create': {'method': 'post',
                           'path': '/usergroups.create'},
    'usergroups__disable': {'method': 'post',
                            'path': '/usergroups.disable'},
    'usergroups__enable': {'method': 'post',
                           'path': '/usergroups.enable'},
    'usergroups__list': {'method': 'post',
                         'path': '/usergroups.list'},
    'usergroups__update': {'method': 'post',
                           'path': '/usergroups.update'},
    'usergroups__users__list': {'method': 'post',
                                'path': '/usergroups.users.list'},
    'usergroups__users__update': {'method': 'post',
                                  'path': '/usergroups.users.update'},
    'users__delete_photo': {'method': 'post',
                           'path': '/users.deletePhoto'},
    'users__get_presence': {'method': 'post',
                           'path': '/users.getPresence'},
    'users__identity': {'method': 'post',
                        'path': '/users.identity'},
    'users__info': {'method': 'post',
                    'path': '/users.info'},
    'users__list': {'method': 'post',
                    'path': '/users.list'},
    'users__set_active': {'method': 'post',
                         'path': '/users.setActive'},
    'users__set_photo': {'method': 'post',
                        'path': '/users.setPhoto'},
    'users__set_presence': {'method': 'post',
                           'path': '/users.setPresence'},
    'users__profile__get': {'method': 'post',
                            'path': '/users.profile.get'},
    'users__profile__set': {'method': 'post',
                            'path': '/users.profile.set'}
}
